### ISSUE TITLE
Getting GitHub Jekyll warnings of CNAME taken

### ISSUE THREAD

**Issue by mpaluchowski** [WarsawIO/warsaw.io#15]
Ever since I'm watching this repository, I'm getting emails from GitHub reporting warnings from the page build process:

> The page build completed successfully, but returned the following warning:
> 
> CNAME already taken: warsaw.io
> 
> For information on troubleshooting Jekyll see:
> 
>  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
> 
> If you have any questions please contact us at https://github.com/contact.

**Comment by wojtekerbetowski** [comment]
Michał, it's because you forked the repo and there's a taken CNAME in yours. That's a frustrating bug from GH Pages. Prob. the best is to either:
- close the repo
- delete/change CNAME file
- change branch name from gh-pages to anything else

Sorry for the inconvenience, you probably should submit a bug to GH Pages.

**Comment by mpaluchowski** [comment]
Ah, I get it. I never used GitHub Pages before and didn't realize the warnings came from my own fork. Thanks for the explanation. This one's for closing then.
